version: '3.8'
volumes:
  odoo13-file-data:
  odoo13-db-data:
services:
  odoo13:
    build: .
    depends_on:
      - odoo13db
    volumes:
      - odoo13-file-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo13db
  odoo13db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo13-db-data:/var/lib/postgresql/data
